module.exports = {
  BASE_URL: process.env.REACT_APP_BASE_URL,
  DRIBBBLE_AUTH_KEY: process.env.REACT_APP_DRIBBBLE_AUTH_KEY,
  ARUN_IMAGE_DESKTOP: process.env.REACT_APP_ARUN_IMAGE_DESKTOP,
  MEDIUM_PROFILE_FEED: process.env.REACT_APP_MEDIUM_PROFILE_FEED,
  WHATSAPP_LINK: process.env.REACT_APP_WHATSAPP_LINK,
  RESUME_LINK: process.env.REACT_APP_RESUME_LINK,
  ARUN_IMAGE_MOBILE: process.env.REACT_APP_ARUN_IMAGE_MOBILE,
};
